spring:
  application:
    name: service-oa
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # ------------ redis -----------------------------
  redis:
    host: 192.168.11.100
    port: 6379
    database: 0
    timeout: 1800000
    password: 111111
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

  # --------- Activity ----------------------------
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: true
