spring:
  application:
    name: service-oa
  profiles:
    active: dev # 激活 dspring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 解决 2.6 的兼容 knife4j 的问题

# ------------ 配置 redis -----------------------------
  redis:
    host: 192.168.11.100
    port: 6379
    database: 0
    timeout: 1800000
    password: 111111
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲